"""
Generate test/regression.toml from the nes-test-roms submodule.

Reads nes-test-roms/status.txt (a `|`-delimited table) to learn each ROM's
reference-emulator result, then emits one [[tests]] entry per .nes file found
in the submodule. Most entries default to expected="skip" (not yet validated
by this emulator); a small OVERRIDES map records the ROMs we have actually
verified.

If test/regression.toml already exists, its per-id `expected`/`note` values are
preserved, so manual curation is never lost on regeneration.

Usage (after `git submodule update --init`):
    python test/gen_config.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SUBMODULE = os.path.join(ROOT, "nes-test-roms")
STATUS = os.path.join(SUBMODULE, "status.txt")
OUT = os.path.join(ROOT, "test", "regression.toml")

# ROMs this emulator has been verified against. Keyed by id (basename without
# .nes; collisions get a parent-dir prefix, matching the id scheme below).
# expected = our current baseline outcome.
OVERRIDES = {
    "apu_test": "pass",
    "03-dummy_reads": "pass",
    "04-dummy_reads_apu": "pass",
    "10-even_odd_timing": "fail",
}

# Heavy ROMs that need more frames to reach a verdict.
HEAVY = {
    "official_only",          # instr_test-v3 / instr_test-v5 official_only.nes
}
HEAVY_FRAMES = 5400


def parse_status(path):
    """Return {basename: reference_result} from status.txt.

    status.txt is a MediaWiki-style `|`-delimited table. Column 0 (after the
    leading empty from the opening `|`) is the NESICIDE result and column 5 is
    the ROM path (backslash-separated). We key the map by lower-cased basename
    so it lines up with the ids we derive below.
    """
    out = {}
    if not os.path.exists(path):
        return out
    with open(path, encoding="utf-8", errors="replace") as f:
        for line in f:
            if "^" in line or not line.strip().startswith("|"):
                continue
            toks = [t.strip() for t in line.split("|")]
            # ['', NESICIDE, Nestopia, Nintendulator, Notes, ROMPath, Other, '']
            if len(toks) < 6:
                continue
            rom = toks[5]
            if not rom.lower().endswith(".nes"):
                continue
            ref = toks[1] if len(toks) > 1 else ""
            out[os.path.basename(rom).lower()] = ref
    return out


def scan_nes(root):
    found = []
    for dirpath, _, files in os.walk(root):
        for fn in files:
            if fn.lower().endswith(".nes"):
                full = os.path.join(dirpath, fn)
                rel = os.path.relpath(full, ROOT).replace(os.sep, "/")
                found.append(rel)
    return sorted(found)


def derive_id(rel, seen):
    """Stable, collision-free id from a submodule-relative path."""
    rel = rel[len("nes-test-roms/"):] if rel.startswith("nes-test-roms/") else rel
    rid = os.path.splitext(rel)[0]            # drop .nes + dirs
    base = os.path.basename(rid)
    if base not in seen:
        seen.add(base)
        return base
    # collision: prefix with the immediate parent directory
    parent = os.path.basename(os.path.dirname(rel))
    candidate = f"{parent}_{base}"
    while candidate in seen:
        candidate = f"_{candidate}"
    seen.add(candidate)
    return candidate


def main():
    refs = parse_status(STATUS)
    roms = scan_nes(SUBMODULE)
    if not roms:
        print(f"No .nes files found under {SUBMODULE}.")
        print("Run `git submodule update --init` first, then retry.")
        return 1

    # preserve existing curation by id
    existing = {}
    if os.path.exists(OUT):
        try:
            import tomllib
            with open(OUT, "rb") as f:
                cfg = tomllib.load(f)
            for t in cfg.get("tests", []):
                existing[t["id"]] = t
        except Exception:
            pass

    lines = [
        "# NES emulator regression suite -- generated by test/gen_config.py",
        "# Run `python test/run_regression.py` to execute the gated tests.",
        "",
        "[settings]",
        "frames = 1200",
        'detector = "blargg"',
        "",
    ]
    seen = set()
    for rel in roms:
        rid = derive_id(rel, seen)
        base = os.path.splitext(os.path.basename(rel))[0]
        ref = refs.get(os.path.basename(rel).lower(), "")
        expected = OVERRIDES.get(rid, "skip")
        frames = HEAVY_FRAMES if base in HEAVY else 1200

        cur = existing.get(rid)
        if cur:
            expected = cur.get("expected", expected)

        lines.append("[[tests]]")
        lines.append(f'id = "{rid}"')
        lines.append(f'path = "{rel}"')
        if frames != 1200:
            lines.append(f"frames = {frames}")
        lines.append(f'expected = "{expected}"')
        if ref:
            lines.append(f'reference = "{ref}"')
        lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    n_pass = sum(1 for l in lines if 'expected = "pass"' in l)
    n_fail = sum(1 for l in lines if 'expected = "fail"' in l)
    skipped = len(roms) - n_pass - n_fail
    print(f"Wrote {OUT}: {len(roms)} ROMs "
          f"({n_pass} pass / {n_fail} fail / {skipped} skip).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
